---
title: "R Markdown networkD3"
output:
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

## simpleNetwork

```{r}
library(networkD3)
src <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
networkData <- data.frame(src, target)
simpleNetwork(networkData)
```


## forceNetwork

```{r}
data(MisLinks)
data(MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4)
```


# sankeyNetwork

```{r}
# v0.4 JSONtoDF depricated ?
# URL <- "https://raw.githubusercontent.com/christophergandrud/d3Network/sankey/JSONdata/energy.json"
# Energy <- RCurl::getURL(URL, ssl.verifypeer = FALSE)
# EngLinks <- JSONtoDF(jsonStr = Energy, array = "links")
# EngNodes <- JSONtoDF(jsonStr = Energy, array = "nodes")
# 
# sankeyNetwork(Links = EngLinks, Nodes = EngNodes, Source = "source",
#               Target = "target", Value = "value", NodeID = "name",
#               fontSize = 12, nodeWidth = 30)

# Recreate Bostock Sankey diagram: http://bost.ocks.org/mike/sankey/
# Load energy projection data
URL <- paste0("https://cdn.rawgit.com/christophergandrud/networkD3/",
              "master/JSONdata/energy.json")
Energy <- jsonlite::fromJSON(URL)

# Plot
sankeyNetwork(Links = Energy$links, Nodes = Energy$nodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             units = "TWh", fontSize = 12, nodeWidth = 30)


```

# diagonalNetwork

```{r}
Flare <- RCurl::getURL("https://gist.githubusercontent.com/mbostock/4063550/raw/a05a94858375bd0ae023f6950a2b13fac5127637/flare.json")
Flare <- rjson::fromJSON(Flare)
diagonalNetwork(List = Flare, fontSize = 10, opacity = 0.9, margin=0)
```

# radialNetwork

```{r}
Flare <- RCurl::getURL("https://gist.githubusercontent.com/mbostock/4063550/raw/a05a94858375bd0ae023f6950a2b13fac5127637/flare.json")
Flare <- rjson::fromJSON(Flare)
radialNetwork(List = Flare, fontSize = 10, opacity = 0.9, margin=0)
```

# dendroNetwork

```{r}
hc <- hclust(dist(USArrests), "ave")
dendroNetwork(hc, height = 600)
```