---
title: "Notes to AES Article"
author: "Jeff Norville"
bibliography: C:/Users/Norville/Documents/Bibliotheque/INRA-2018.bib
output: 
  html_document:
    toc: yes
  pdf_document:
    toc: yes

link-citations: yes
biblio-style: apalike
---

## Read D1.1 Table
```{r}
library(readxl)
library(networkD3)
library(igraph)


aes_links <- read_excel("C:/Users/Norville/Dropbox/API-SMAL_Partage_Animation/Livrables/D1.1_List_of_AES_English.xlsm",
                  sheet = "links", skip = 1)
aes_nodes <- read_excel("C:/Users/Norville/Dropbox/API-SMAL_Partage_Animation/Livrables/D1.1_List_of_AES_English.xlsm",
                        sheet = "nodes", skip = 1)
net <- graph_from_data_frame(d=aes_links, vertices=aes_nodes, directed=T) 

plot(net)

```


## Prairie
```{r}

require(visNetwork, quietly = TRUE)
# minimal example
nodes <- data.frame(c("Prairie (vs cropland)",
"Prairies",
"Adding grasslands to Landscape (leys in particular)",
"Adding grasslands to Landscape (meadows, pastures, permanent grasslands, semi-natural grasslands)"))
edges <- data.frame(from = c(1,2), to = c(1,3))
visNetwork(nodes, edges, width = "100%")

```

## Forest
```{r}

library(networkD3)
src <- c("Biodiversity", "Biodiversity", "Biodiversity", "Biodiversity", "Reduce GHG Emissions", "Reduce GHG Emissions", "Reduce soil, water pollution", "Reduce soil, water pollution", "Soil fertility")
target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
networkData <- data.frame(src, target)
simpleNetwork(networkData)
```



## simpleNetwork

```{r}
library(networkD3)
src <- c("A", "A", "A", "A", "B", "B", "C", "C", "D")
target <- c("B", "C", "D", "J", "E", "F", "G", "H", "I")
networkData <- data.frame(src, target)
simpleNetwork(networkData)
```


## forceNetwork

```{r}
data(MisLinks)
data(MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes, Source = "source",
             Target = "target", Value = "value", NodeID = "name",
             Group = "group", opacity = 0.4, zoom = TRUE)
```




## Intro


I'll add figures for the D1.1 table inline here, then we can collaberate in-line below.

Can I add datatables too?

=======

Practice a citation like @Bayer2019




